### PR TITLE
Update node runtime (v20) / dependencies

### PR DESCRIPTION
**Pull request by miguelnv**
This PR aims to bump actions node version (v20) and dependencies due to node 16 runtime deprecation. https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

### CODE REVIEW

**Comment by arden828** [comment]
Can we get this one released, please.

**Comment by bhicks** [comment]
@fishcharlie is there anything I can do to help merge this PR?

**Comment by fishcharlie** [comment]
@bhicks https://github.com/rrainn/dynamodb-action/releases/tag/v4.0.0. That work for you? 😉

**Comment by bhicks** [comment]
@fishcharlie wow! thank you for the lightning fast response!

**Pull request merged**
